[package]
name = "isabelle-plugin-security"
version = "1.17.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
isabelle-dm = { "git" = "https://github.com/isabelle-platform/isabelle-dm", tag = "1.9.0" }
isabelle-plugin-api = { "git" = "https://github.com/isabelle-platform/isabelle-plugin-api", tag = "1.20.0" }
log = "0.4.0"
serde_urlencoded = "0.7"
image = "0.25.9"
