[package]
name = "isabelle-plugin-security"
version = "1.13.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
isabelle-dm = { "git" = "https://github.com/isabelle-platform/isabelle-dm", tag = "1.7.0" }
isabelle-plugin-api = { "git" = "https://github.com/isabelle-platform/isabelle-plugin-api", tag = "1.16.0" }
log = "0.4.0"
